/**
 * Lingola Stories — yerel bildirim metinleri
 * Ton: kitap ayracı, acele ettirmeyen, kısa, nokta ile biten
 * Emoji: yalnızca CURIOUS listesinde tek örnek (👀)
 */

const NOTIFICATION_MESSAGES = {
  SOFT: {
    delayHours: 2,
    tone: "soft",
    tr: [
      "Biraz ara verdin.",
      "Hikâye orada kaldı.",
      "Kısa bir okuma molası vermiş olabilirsin.",
      "Buradayız, sayfa kapanmadı.",
      "Sessiz bir an vardı.",
    ],
    en: [
      "You took a little break.",
      "The story stayed right there.",
      "Maybe a short reading pause.",
      "We're here. The page is still open.",
      "A quiet moment passed.",
    ],
    de: [
      "Du hast eine kleine Pause gemacht.",
      "Die Geschichte ist dort geblieben.",
      "Vielleicht eine kurze Lesepause.",
      "Wir sind da. Die Seite ist noch offen.",
      "Ein stiller Moment war da.",
    ],
    es: [
      "Tomaste un pequeño descanso.",
      "La historia se quedó ahí.",
      "Quizá una pausa breve de lectura.",
      "Seguimos aquí. La página sigue abierta.",
      "Hubo un momento de calma.",
    ],
    fr: [
      "Tu as fait une petite pause.",
      "L'histoire est restée là.",
      "Peut-être une courte pause de lecture.",
      "Nous sommes là. La page est encore ouverte.",
      "Un moment de calme est passé.",
    ],
    it: [
      "Hai fatto una piccola pausa.",
      "La storia è rimasta lì.",
      "Forse una breve pausa di lettura.",
      "Siamo qui. La pagina è ancora aperta.",
      "C'è stato un momento di quiete.",
    ],
    pt: [
      "Você fez uma pequena pausa.",
      "A história ficou ali.",
      "Talvez uma breve pausa na leitura.",
      "Estamos aqui. A página ainda está aberta.",
      "Houve um momento de calma.",
    ],
    ru: [
      "Ты сделал небольшую паузу.",
      "История осталась на месте.",
      "Может быть, короткий перерыв в чтении.",
      "Мы здесь. Страница всё ещё открыта.",
      "Был тихий момент.",
    ],
    az: [
      "Kiçik bir fasilə verdin.",
      "Hekayə orada qaldı.",
      "Bəlkə qısa bir oxuma fasiləsi.",
      "Buradayıq. Səhifə hələ açıqdır.",
      "Sakit bir an var idi.",
    ],
    ko: [
      "잠깐 쉬었네요.",
      "이야기는 그 자리에 있어요.",
      "짧은 읽기 휴식일지도요.",
      "우리는 여기 있어요. 페이지는 아직 열려 있어요.",
      "조용한 순간이 있었어요.",
    ],
    hi: [
      "आपने थोड़ा विश्राम लिया।",
      "कहानी वहीं रुकी है।",
      "शायद एक छोटा पढ़ने का विराम।",
      "हम यहाँ हैं। पन्ना अभी भी खुला है।",
      "एक शांत पल गुज़रा।",
    ],
    ja: [
      "少し休憩したね。",
      "物語はそこに留まっている。",
      "短い読書の休憩かもしれない。",
      "ここにいるよ。ページはまだ開いている。",
      "静かなひとときがあった。",
    ],
  },
  CURIOUS: {
    delayHours: 4,
    tone: "curious",
    tr: [
      "Hikâye tam bir yerde kaldı 👀",
      "Bir karakter seni bekliyor olabilir.",
      "Bir sonraki satır okunmadı.",
      "Hikâyede bir şey oldu ama devam etmedin.",
      "Küçük bir bölüm yarım kaldı.",
    ],
    en: [
      "The story paused at a certain point 👀",
      "A character might still be there.",
      "The next line is still unread.",
      "Something happened in the story. You stepped away.",
      "A small part is still unfinished.",
    ],
    de: [
      "Die Geschichte blieb an einer Stelle stehen 👀",
      "Vielleicht wartet noch eine Figur.",
      "Die nächste Zeile ist noch ungelesen.",
      "In der Geschichte passierte etwas. Du bist weggegangen.",
      "Ein kleiner Teil ist noch offen.",
    ],
    es: [
      "La historia se detuvo en un punto 👀",
      "Un personaje podría seguir ahí.",
      "La siguiente línea sigue sin leerse.",
      "Algo pasó en la historia. Te fuiste un momento.",
      "Una pequeña parte quedó a medias.",
    ],
    fr: [
      "L'histoire s'est arrêtée à un endroit 👀",
      "Un personnage t'attend peut-être encore.",
      "La ligne suivante n'a pas été lue.",
      "Quelque chose s'est passé dans l'histoire. Tu t'es éloigné.",
      "Une petite partie est restée inachevée.",
    ],
    it: [
      "La storia si è fermata in un punto 👀",
      "Un personaggio potrebbe essere ancora lì.",
      "La riga successiva non è stata letta.",
      "Qualcosa è successo nella storia. Ti sei allontanato.",
      "Una piccola parte è rimasta incompleta.",
    ],
    pt: [
      "A história parou em um ponto 👀",
      "Um personagem pode ainda estar lá.",
      "A próxima linha ainda não foi lida.",
      "Algo aconteceu na história. Você se afastou.",
      "Uma pequena parte ficou pela metade.",
    ],
    ru: [
      "История остановилась в одном месте 👀",
      "Возможно, персонаж всё ещё ждёт.",
      "Следующая строка ещё не прочитана.",
      "В истории что-то произошло. Ты отошёл.",
      "Небольшая часть осталась незаконченной.",
    ],
    az: [
      "Hekayə tam bir yerdə qaldı 👀",
      "Bir personaj səni gözləyir ola bilər.",
      "Növbəti sətir oxunmadı.",
      "Hekayədə bir şey oldu. Getdin.",
      "Kiçik bir hissə yarım qaldı.",
    ],
    ko: [
      "이야기가 한곳에서 멈춰 있어요 👀",
      "어떤 인물이 기다리고 있을지도요.",
      "다음 줄은 아직 읽히지 않았어요.",
      "이야기에 무언가 일어났어요. 잠시 자리를 비우셨네요.",
      "작은 부분이 중간에 멈춰 있어요.",
    ],
    hi: [
      "कहानी एक जगह रुक गई 👀",
      "कोई पात्र शायद अभी भी वहीं है।",
      "अगली पंक्ति अभी पढ़ी नहीं गई।",
      "कहानी में कुछ हुआ। आप चले गए।",
      "एक छोटा हिस्सा अधूरा रह गया।",
    ],
    ja: [
      "物語がとある場所で止まっている 👀",
      "キャラクターがまだ待っているかもしれない。",
      "次の行はまだ読まれていない。",
      "物語で何かが起きた。少し離れたね。",
      "小さな部分が途中のままだ。",
    ],
  },
  SUPPORT: {
    delayHours: 8,
    tone: "support",
    tr: [
      "Bugün okumadıysan da sorun değil.",
      "Hikâyeler bekler.",
      "Bazen sadece okumak yeterlidir.",
      "Zihnin dinlenmek istemiş olabilir.",
      "İstersen sadece birkaç satır.",
    ],
    en: [
      "It's okay if you didn't read today.",
      "Stories wait.",
      "Sometimes reading a little is enough.",
      "Your mind may have wanted rest.",
      "A few lines are enough, if you like.",
    ],
    de: [
      "Es ist in Ordnung, wenn du heute nicht gelesen hast.",
      "Geschichten warten.",
      "Manchmal reicht ein wenig Lesen.",
      "Dein Geist wollte vielleicht ruhen.",
      "Ein paar Zeilen reichen, wenn du möchtest.",
    ],
    es: [
      "No pasa nada si hoy no leíste.",
      "Las historias esperan.",
      "A veces basta con leer un poco.",
      "Tu mente quizá quiso descansar.",
      "Unas líneas bastan, si quieres.",
    ],
    fr: [
      "Ce n'est pas grave si tu n'as pas lu aujourd'hui.",
      "Les histoires attendent.",
      "Parfois, lire un peu suffit.",
      "Ton esprit a peut-être voulu se reposer.",
      "Quelques lignes suffisent, si tu veux.",
    ],
    it: [
      "Va bene se oggi non hai letto.",
      "Le storie aspettano.",
      "A volte basta leggere un po'.",
      "La tua mente forse voleva riposare.",
      "Bastano poche righe, se vuoi.",
    ],
    pt: [
      "Tudo bem se você não leu hoje.",
      "As histórias esperam.",
      "Às vezes, ler um pouco basta.",
      "Sua mente talvez quis descansar.",
      "Algumas linhas bastam, se quiser.",
    ],
    ru: [
      "Ничего страшного, если сегодня не читал.",
      "Истории подождут.",
      "Иногда достаточно прочитать немного.",
      "Твоему разуму, возможно, нужен был отдых.",
      "Нескольких строк достаточно, если захочешь.",
    ],
    az: [
      "Bu gün oxumasan da problem deyil.",
      "Hekayələr gözləyir.",
      "Bəzən az oxumaq kifayətdir.",
      "Zehnin istirahət istəmiş ola bilər.",
      "Bir neçə sətir kifayətdir, istəsən.",
    ],
    ko: [
      "오늘 읽지 않아도 괜찮아요.",
      "이야기들은 기다려요.",
      "가끔은 조금만 읽어도 충분해요.",
      "마음이 쉬고 싶었을지도요.",
      "원하시면 몇 줄이면 돼요.",
    ],
    hi: [
      "आज न पढ़ें तो भी ठीक है।",
      "कहानियाँ इंतज़ार करती हैं।",
      "कभी-कभी थोड़ा पढ़ना काफ़ी है।",
      "आपके मन को विश्राम चाहिए होगा।",
      "चाहें तो कुछ पंक्तियाँ काफ़ी हैं।",
    ],
    ja: [
      "今日読まなくても大丈夫。",
      "物語は待っている。",
      "少し読むだけでも十分なことがある。",
      "心が休みたがっていたのかも。",
      "数行だけでも、よければ。",
    ],
  },
  REMAINDER: {
    delayHours: 24,
    tone: "bookmark",
    tr: [
      "Bir gün geçti. Hikâye burada.",
      "Kaldığın sayfa duruyor.",
      "Ara verdin, sorun değil.",
      "Ne zaman açarsan.",
      "Hikâye kaçmadı.",
    ],
    en: [
      "A day passed. The story is still here.",
      "The page you left is still there.",
      "You paused. That's okay.",
      "Whenever you open it again.",
      "The story didn't go away.",
    ],
    de: [
      "Ein Tag ist vergangen. Die Geschichte ist noch da.",
      "Die Seite, die du offen ließest, wartet.",
      "Du hast pausiert. Das ist in Ordnung.",
      "Wann immer du wieder öffnest.",
      "Die Geschichte ist nicht weg.",
    ],
    es: [
      "Pasó un día. La historia sigue aquí.",
      "La página donde te quedaste sigue ahí.",
      "Hiciste una pausa. No pasa nada.",
      "Cuando quieras abrirla de nuevo.",
      "La historia no se fue.",
    ],
    fr: [
      "Un jour est passé. L'histoire est toujours là.",
      "La page où tu t'es arrêté attend encore.",
      "Tu as fait une pause. Ce n'est pas grave.",
      "Quand tu voudras l'ouvrir à nouveau.",
      "L'histoire n'est pas partie.",
    ],
    it: [
      "È passato un giorno. La storia è ancora qui.",
      "La pagina dove eri rimasto aspetta.",
      "Hai fatto una pausa. Va bene così.",
      "Quando vorrai riaprirla.",
      "La storia non è andata via.",
    ],
    pt: [
      "Um dia passou. A história ainda está aqui.",
      "A página onde você parou continua lá.",
      "Você fez uma pausa. Tudo bem.",
      "Quando quiser abrir de novo.",
      "A história não foi embora.",
    ],
    ru: [
      "Прошёл день. История всё ещё здесь.",
      "Страница, на которой ты остановился, на месте.",
      "Ты сделал паузу. Это нормально.",
      "Когда захочешь открыть снова.",
      "История никуда не делась.",
    ],
    az: [
      "Bir gün keçdi. Hekayə buradadır.",
      "Qaldığın səhifə gözləyir.",
      "Fasilə verdin. Problem deyil.",
      "Nə vaxt açsan.",
      "Hekayə getmədi.",
    ],
    ko: [
      "하루가 지났어요. 이야기는 여기 있어요.",
      "멈춘 페이지는 그대로예요.",
      "쉬었어요. 괜찮아요.",
      "언제든 다시 열면 돼요.",
      "이야기는 사라지지 않았어요.",
    ],
    hi: [
      "एक दिन बीत गया। कहानी यहीं है।",
      "जहाँ रुके थे, वह पन्ना अभी भी है।",
      "आपने विराम लिया। कोई बात नहीं।",
      "जब चाहें फिर खोलें।",
      "कहानी चली नहीं गई।",
    ],
    ja: [
      "一日が過ぎた。物語はここにある。",
      "止めたページはそのまま。",
      "休憩した。大丈夫。",
      "開きたくなったときに。",
      "物語は消えていない。",
    ],
  },
};

const SUPPORTED_LANGS = [
  "tr",
  "en",
  "de",
  "es",
  "fr",
  "it",
  "pt",
  "ru",
  "az",
  "ko",
  "hi",
  "ja",
];

/** Marka adı tüm dillerde aynı kalır */
const NOTIFICATION_TITLES = {
  tr: "Lingola Stories",
  en: "Lingola Stories",
  de: "Lingola Stories",
  es: "Lingola Stories",
  fr: "Lingola Stories",
  it: "Lingola Stories",
  pt: "Lingola Stories",
  ru: "Lingola Stories",
  az: "Lingola Stories",
  ko: "Lingola Stories",
  hi: "Lingola Stories",
  ja: "Lingola Stories",
};

module.exports = {
  NOTIFICATION_MESSAGES,
  NOTIFICATION_TITLES,
  SUPPORTED_LANGS,
};
